### ISSUE TITLE
error: "undefined symbol " when import "containerd" package

### ISSUE THREAD

**Issue by xiaozhouX** [NVIDIA/go-nvml#18]
We have a Golang application use `github.com/NVIDIA/go-nvml/pkg/nvml`.  After import `containerd` package, the application will shutdown and throw an error  `symbol lookup error`.

I write a sample, which trigger the same error:
```
package main

import (
	"github.com/NVIDIA/go-nvml/pkg/nvml"
	"github.com/containerd/containerd"
)

func main() {
	_, err := containerd.New(".....")
	if err != nil {
		println("containerd new err", err.Error())
		return
	}
	ret := nvml.Init()
	if ret != nvml.SUCCESS {
		println("Unable to initialize NVML: %v", nvml.ErrorString(ret))
	}
	return
}

```
Then the error show up: 
`symbol lookup error: /app/test : undefined symbol: nvmlGpuInstanceGetComputeInstanceById`

Same as issue:
[#137](https://github.com/NVIDIA/nvidia-container-runtime/issues/137)

**Comment by klueska** [comment]
Interesting.

This function `nvmlGpuInstanceGetComputeInstanceById()` was only introduced in NVML v11.0 (i.e. driver version 450+), but these binding should work fine (even on older drivers), so long these newer functions are never called.

That said -- I _**am**_ able to reproduce your error on a machine I have with the 410 driver.
And it only happens when `containerd` is imported / used....

Something inside `containerd` must be triggering this to be called for some reason.

I will need to investigate further.

**Comment by klueska** [comment]
It's not ideal, and I haven't gotten to the bottom of exactly what causes this to be necessary in the case of pulling in containerd (or more likely one of the other dependencies it pulls in...), but if you compile your program with the following, it should resolve your issue:
```
go build -ldflags="-extldflags=-Wl,-z,lazy" test.go
```

**Comment by klueska** [comment]
Was this able to resolve your issue?

**Comment by xiaozhouX** [comment]
> Was this able to resolve your issue?

Yes, I have tested in my program just now,  it resolve my problem.
Thanks a lot for your help !!

**Comment by hhhhappy** [comment]
Any conclusion on this issues? Problem solved but still confused

**Comment by pgimalac** [comment]
I believe this is due to `containerd` v1 importing the `plugin` package (which changes a lot of things in the Go build/link steps).
See https://github.com/containerd/containerd/issues/11202 for some more details.

You can add the build tag `no_dynamic_plugins` to avoid the import in containerd, which should fix it.
