### ISSUE TITLE
hould we consider employing sync.Once to ensure that Init and Shutdown are executed only once?

### ISSUE THREAD

**Issue by LambdaHJ** [NVIDIA/go-nvml#74]
Like this 
```
var initError Return = SUCCESS
var intOnce sync.Once

// nvml.Init()
func Init() Return {
	intOnce.Do(func() {
		lib := dl.New(nvmlLibraryName, nvmlLibraryLoadFlags)
		err := lib.Open()
		if err != nil {
			initError = ERROR_LIBRARY_NOT_FOUND
		}
		nvml = lib
		updateVersionedSymbols()
		nvmlInit()
	})

	return initError
}
```

**Comment by klueska** [comment]
I don't think we want to prevent someone from shutting down and reinitializing NVML without restarting their program. This would be required, for example, if someone were to reload the nvidia kernel module.

**Comment by elezar** [comment]
@LambdaHJ I believe that with the latest iterations of the bindings and specifically #105, this should no longer be required.

Note that there was a bug in how we were handling the underlying dynamic library and you may have been seeing issues due to this.

I'm closing this issue as resolved, but please reopen it if you're still having problems.
